name: Yeni Robot Calistir

on:
  schedule:
    - cron: '30 15 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install yfinance pandas requests
      - run: python borsa_robotu_yeni.py
      - run: |
          git config --global user.name "HasanBot"
          git config --global user.email "bot@hasan.com"
          git add analiz_yeni.html
          git commit -m "Uclu analiz guncellendi" || exit 0
          git push
